# **Projeto de Estatística: Análise Exploratória de Dados da PRF**

Análise e exploração de dados da Polícia Rodoviária Federal para identificar padrões e características presentes nos dados de acidentes e multas.

In [1]:
#Importação da biblioteca Pandas como pd
import pandas as pd

#Importação da biblioteca Numpy para operações matemáticas
import numpy as np

**Aluno: Thales Trajano Farias**

**Dataset utilizado: `Acidentes (agrupados por pessoas)` e `Multas` ano de 2018-2019**

## **Importação dos DataFrames**

OBS: Optei por colocar todos os arquivos em variáveis, e todos em uma única célula, para facilitar caso haja mudança futura no caminho dos arquivos.

In [2]:
acidentes1='Acidentes/acidentes2019.csv'
acidentes2='Acidentes/acidentes2018.csv'

Eu optei por escolher os acidentes agrupados por ocorrência. Nesse  caso a maioria dos arquivos eram separados por ponto e vírgula e tinham codificação diferente da padrão `UTF-8`, eles usavam o `latin1`

In [3]:
df1= pd.read_csv(acidentes1,
                sep=';',
                encoding='latin1')

In [4]:
df2= pd.read_csv(acidentes2,
                sep=';',
                encoding='latin1')

## **Importação dos arquivos de multa**

OBS: Fiz a mesma coisa que na importação passada e coloquei todos em variáveis e na mesma célula para facilitar caso haja mudança no caminho do arquivo.

In [5]:
multa1= 'Infrações.2018-2025/infraçoes2019_01.csv'
multa2= 'Infrações.2018-2025/infraçoes2018_01.csv'

Alguns arquivos estavam dando erro porque o `Pandas` identificava uma coluna com um tipo de valor e depois se deparava com outro valor diferente, então tava dando um aviso de erro mesmo que a tabela rodasse. Para evitar esse aviso, botei o argumento `low_memory=False`

In [6]:
t1= pd.read_csv(multa1, 
                sep=';', 
                encoding='utf-8',
                low_memory=False
                )
t1

,Número do Auto,Data da Infração (DD/MM/AAAA),Indicador de Abordagem,Assinatura do Auto,Indicador Veiculo Estrangeiro,Sentido Trafego,UF Placa,UF Infração,BR Infração,Km Infração,...,Descrição Abreviada Infração,Enquadramento da Infração,Início Vigência da Infração,Fim Vigência Infração,Medição Infração,Descrição Especie Veículo,Descrição Marca Veículo,Hora Infração,Medição Considerada,Excesso Verificado
0,5bcd39ea93ac463,2019-01-06,C,N,S,C,-1,PR,369,132,...,Transportar criança sem observância das normas...,168,2016-11-01,NaN,Nenhuma,PASSAGEIRO,FORD,18,0.00,0.00
1,e038e26abee1b3f,2019-01-20,C,N,N,D,-1,RJ,356,169,...,Conduzir veíc com vidro total/parcialmente cob...,230 XVI,2016-11-01,NaN,Nenhuma,PASSAGEIRO,OUTRA,16,0.00,0.00
2,e4881fa47a05ae9,2019-01-20,C,N,N,D,-1,RJ,356,169,...,Conduzir o veículo com característica alterada,230 VII,2016-11-01,NaN,Nenhuma,PASSAGEIRO,OUTRA,16,0.00,0.00
3,d6c91fa499ca5fd,2019-01-04,C,N,N,C,GO,GO,50,286,...,"Em movimento de dia, deixar de manter acesa lu...",250 I b,2016-11-01,NaN,Nenhuma,MISTO,OUTRA,9,0.00,0.00
4,8af020201f2bebf,2019-01-04,C,N,N,D,RS,PR,116,98,...,Deixar reduzir velocidade nas vias rurais cuja...,220 V,2016-11-01,NaN,Nenhuma,CARGA,MERCEDES BENZ,3,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518471,72f9e82522e0e43,2019-01-31,S,N,N,D,-1,SC,470,47,...,"Em movimento de dia, deixar de manter acesa lu...",250 I b,2016-11-01,NaN,Nenhuma,PASSAGEIRO,HONDA,18,0.00,0.00
518472,92d0eaba36f5d71,2019-01-31,S,N,N,D,-1,SC,470,47,...,"Em movimento de dia, deixar de manter acesa lu...",250 I b,2016-11-01,NaN,Nenhuma,PASSAGEIRO,FORD,18,0.00,0.00
518473,3333cf0abfc1750,2019-01-31,S,N,N,D,-1,SC,470,49,...,"Em movimento de dia, deixar de manter acesa lu...",250 I b,2016-11-01,NaN,Nenhuma,CARGA,MERCEDES BENZ,18,0.00,0.00
518474,1313c930ab1b01f,2019-01-31,S,N,N,D,-1,SC,470,49,...,"Em movimento de dia, deixar de manter acesa lu...",250 I b,2016-11-01,NaN,Nenhuma,CARGA,OUTRA,18,0.00,0.00
518475,213b636d4d273e2,2019-01-31,S,N,N,D,-1,SC,470,49,...,"Em movimento de dia, deixar de manter acesa lu...",250 I b,2016-11-01,NaN,Nenhuma,PASSAGEIRO,VW,18,0.00,0.00

In [7]:
t2 = pd.read_csv(multa2,
                 sep=',',
                 encoding='latin1',
                 low_memory=False
                 )

## **Comparação entre as tabelas de Multas e Acidentes**

Apesar de possuírem objetivos diferentes, as tabelas **Multas** e **Acidentes** apresentam algumas colunas com informações semelhantes.

### Informações em comum

- Ambas possuem uma coluna de **data**, no formato `dd/mm/aaaa`.
- Possuem informações para identificar o **local da ocorrência**, como:
  - **BR**
  - **KM da BR**
- Ambas informam o **município** onde ocorreu o acidente ou a infração.
- Também possuem a **Unidade Federativa (UF)** correspondente à ocorrência.

### Informações específicas

Embora existam semelhanças entre algumas variáveis, cada tabela possui colunas específicas relacionadas ao seu objetivo.

Na tabela de **Acidentes**, são utilizadas colunas como:

- `causa_acidente`
- `tipo_acidente`
- Quantidade de feridos, incluindo:
  - Feridos leves
  - Feridos graves
  - Feridos ignorados
  - Mortos
- Tipo da pista
- Condição meteorológica
- Outras informações relacionadas às características e consequências do acidente.

Já a tabela de **Multas** possui informações relacionadas à fiscalização e às infrações de trânsito, como:

- Informações sobre a abordagem do veículo
- Sentido do tráfego
- Data de início e fim da vigência
- Medição realizada
- `descricao_abreviada`, utilizada para identificar a infração cometida
- Outras informações específicas relacionadas à aplicação das multas.

Embora as duas tabelas compartilhem informações relacionadas ao **tempo e ao local das ocorrências**, suas demais variáveis são voltadas para objetivos distintos: a tabela **Acidentes** apresenta informações sobre ocorrências e suas consequências, enquanto a tabela **Multas** está relacionada à fiscalização e às infrações de trânsito.

## **Concatenação das tabelas**

### **Concatenação das tabelas de acidentes**

A tabela de acidentes já possui colunas com os mesmos nomes em todos os anos, de 2018 até 2025. Então bastou concatenar com o argumento `keys` para criar os multiindex referentes a cada ano.

In [8]:
tabela_acidentes= pd.concat([df1, df2],
                            keys=[2019, 2018],
                           names=['ano', 'indice'])
tabela_acidentes

                   id    pesid data_inversa    dia_semana   horario  uf   br  \
ano  indice
2019 0       182256.0   403856   2019-01-01   terça-feira  04:00:00  CE  116
     1       182263.0   402859   2019-01-01   terça-feira  05:00:00  MT  158
     2       182277.0   402850   2019-01-01   terça-feira  10:00:00  PA   10
     3       182289.0   402431   2019-01-01   terça-feira  08:30:00  BA  101
     4       182307.0   402638   2019-01-01   terça-feira  13:50:00  BA  116
...               ...      ...          ...           ...       ...  ..  ...
2018 180056  593091.0  1321335   2018-11-11       domingo  00:50:00  PR  369
     180057  593091.0  1321333   2018-11-11       domingo  00:50:00  PR  369
     180058  593091.0  1321334   2018-11-11       domingo  00:50:00  PR  369
     180059  594880.0  1325466   2018-05-31  quinta-feira  23:30:00  MG   40
     180060  594880.0  1325467   2018-05-31  quinta-feira  23:30:00  MG   40

                km         municipio                    causa_acidente  ...  \
ano  indice                                                             ...
2019 0       136,9            RUSSAS                  Animais na Pista  ...
     1       599,5          AGUA BOA       Defeito Mecânico no Veículo  ...
     2          34        DOM ELISEU           Velocidade Incompatível  ...
     3          13          RIO REAL                Ingestão de Álcool  ...
     4         440  FEIRA DE SANTANA                Ingestão de Álcool  ...
...            ...               ...                               ...  ...
2018 180056   45,8      BANDEIRANTES  Ingestão de álcool pelo condutor  ...
     180057   45,8      BANDEIRANTES  Ingestão de álcool pelo condutor  ...
     180058   45,8      BANDEIRANTES  Ingestão de álcool pelo condutor  ...
     180059  282,1       TRES MARIAS  Ingestão de álcool pelo condutor  ...
     180060  282,1       TRES MARIAS  Ingestão de álcool pelo condutor  ...

                  sexo ilesos feridos_leves feridos_graves mortos  \
ano  indice
2019 0       Masculino      1             0              0      0
     1       Masculino      1             0              0      0
     2       Masculino      1             0              0      0
     3       Masculino      1             0              0      0
     4       Masculino      0             1              0      0
...                ...    ...           ...            ...    ...
2018 180056  Masculino      0             1              0      0
     180057  Masculino      1             0              0      0
     180058  Masculino      0             1              0      0
     180059  Masculino      0             0              1      0
     180060  Masculino      0             1              0      0

                 latitude     longitude regional  delegacia             uop
ano  indice
2019 0          -4,766018    -38,056034  SPRF-CE   DEL03-CE  UOP01-DEL03-CE
     1            -14,319       -52,169  SPRF-MT   DEL07-MT  UOP02-DEL07-MT
     2        -4,15296734  -47,54608154  SPRF-PA   DEL02-PA  UOP02-DEL02-PA
     3           -11,5896      -37,8761  SPRF-SE   DEL02-SE  UOP03-DEL02-SE
     4            -12,344       -39,087  SPRF-BA   DEL02-BA  UOP01-DEL02-BA
...                   ...           ...      ...        ...             ...
2018 180056  -23,09035157  -50,29617894  SPRF-PR   DEL07-PR  UOP05-DEL07-PR
     180057  -23,09035157  -50,29617894  SPRF-PR   DEL07-PR  UOP05-DEL07-PR
     180058  -23,09035157  -50,29617894  SPRF-PR   DEL07-PR  UOP05-DEL07-PR
     180059    -18,249315    -45,202118  SPRF-MG   DEL14-MG  UOP02-DEL14-MG
     180060    -18,249315    -45,202118  SPRF-MG   DEL14-MG  UOP02-DEL14-MG

[356165 rows x 35 columns]

In [9]:
tabela_acidentes= tabela_acidentes.set_index('id', append=True)
tabela_acidentes = tabela_acidentes.droplevel('indice')
tabela_acidentes.head()

                pesid data_inversa   dia_semana   horario  uf   br     km  \
ano  id
2019 182256.0  403856   2019-01-01  terça-feira  04:00:00  CE  116  136,9
     182263.0  402859   2019-01-01  terça-feira  05:00:00  MT  158  599,5
     182277.0  402850   2019-01-01  terça-feira  10:00:00  PA   10     34
     182289.0  402431   2019-01-01  terça-feira  08:30:00  BA  101     13
     182307.0  402638   2019-01-01  terça-feira  13:50:00  BA  116    440

                      municipio               causa_acidente  \
ano  id
2019 182256.0            RUSSAS             Animais na Pista
     182263.0          AGUA BOA  Defeito Mecânico no Veículo
     182277.0        DOM ELISEU      Velocidade Incompatível
     182289.0          RIO REAL           Ingestão de Álcool
     182307.0  FEIRA DE SANTANA           Ingestão de Álcool

                           tipo_acidente  ...       sexo ilesos feridos_leves  \
ano  id                                   ...
2019 182256.0    Atropelamento de Animal  ...  Masculino      1             0
     182263.0                   Incêndio  ...  Masculino      1             0
     182277.0           Colisão traseira  ...  Masculino      1             0
     182289.0           Colisão traseira  ...  Masculino      1             0
     182307.0  Saída de leito carroçável  ...  Masculino      0             1

              feridos_graves mortos     latitude     longitude  regional  \
ano  id
2019 182256.0              0      0    -4,766018    -38,056034   SPRF-CE
     182263.0              0      0      -14,319       -52,169   SPRF-MT
     182277.0              0      0  -4,15296734  -47,54608154   SPRF-PA
     182289.0              0      0     -11,5896      -37,8761   SPRF-SE
     182307.0              0      0      -12,344       -39,087   SPRF-BA

              delegacia             uop
ano  id
2019 182256.0  DEL03-CE  UOP01-DEL03-CE
     182263.0  DEL07-MT  UOP02-DEL07-MT
     182277.0  DEL02-PA  UOP02-DEL02-PA
     182289.0  DEL02-SE  UOP03-DEL02-SE
     182307.0  DEL02-BA  UOP01-DEL02-BA

[5 rows x 34 columns]

### **Concatenação das tabelas de multas**

A tabela de multas começou com 22 colunas até 2021, em 2022 foi para 25 colunas. Em 2018, no entanto, as colunas tinham nomes diferentes, embora significados iguais, então eu uso o comando `rename` para mudar o nome das colunas de 2018 para seus equivalentes nos anos seguintes

In [10]:
t2 = t2.rename(
    columns={
        'dat_infracao': 'Data da Infração (DD/MM/AAAA)',
        'hora': 'Hora Infração',
        'tip_abordagem': 'Indicador de Abordagem',
        'ind_assinou_auto': 'Assinatura do Auto',
        'ind_veiculo_estrangeiro': 'Indicador Veiculo Estrangeiro',
        'ind_sentido_trafego': 'Sentido Trafego',
        'uf_placa': 'UF Placa',
        'uf_infracao': 'UF Infração',
        'num_br_infracao': 'BR Infração',
        'num_km_infracao': 'Km Infração',
        'nom_municipio': 'Município',
        'cod_infracao': 'Código da Infração',
        'descricao_abreviada': 'Descrição Abreviada Infração',
        'enquadramento': 'Enquadramento da Infração',
        'data_inicio_vigencia': 'Início Vigência da Infração',
        'data_fim_vigencia': 'Fim Vigência Infração',
        'med_realizada': 'Medição Infração',
        'med_considerada': 'Medição Considerada',
        'exc_verificado': 'Excesso Verificado',
        'especie': 'Descrição Especie Veículo',
        'nome_veiculo_marca': 'Descrição Marca Veículo'
    }
)

OBS: como a coluna `nom_modelo_veiculo` só existe na tabela de 2018 e em nenhuma outra dos anos seguintes, eu tirei para evitar uma coluna que praticamente só teria valores `Nan`.

In [11]:
t2 = t2.drop(columns=['nom_modelo_veiculo'])

In [12]:
tabela_multa= pd.concat([t1, t2],
                        keys=[2019, 2018],
                        names=['ano', 'indice'])
tabela_multa

              Número do Auto Data da Infração (DD/MM/AAAA)  \
ano  indice
2019 0       5bcd39ea93ac463                    2019-01-06
     1       e038e26abee1b3f                    2019-01-20
     2       e4881fa47a05ae9                    2019-01-20
     3       d6c91fa499ca5fd                    2019-01-04
     4       8af020201f2bebf                    2019-01-04
...                      ...                           ...
2018 594715              NaN                    2018-01-31
     594716              NaN                    2018-01-31
     594717              NaN                    2018-01-31
     594718              NaN                    2018-01-31
     594719              NaN                    2018-01-31

            Indicador de Abordagem Assinatura do Auto  \
ano  indice
2019 0                           C                  N
     1                           C                  N
     2                           C                  N
     3                           C                  N
     4                           C                  N
...                            ...                ...
2018 594715                      S                NaN
     594716                      S                NaN
     594717                      S                NaN
     594718                      S                NaN
     594719                      S                NaN

            Indicador Veiculo Estrangeiro Sentido Trafego UF Placa  \
ano  indice
2019 0                                  S               C       -1
     1                                  N               D       -1
     2                                  N               D       -1
     3                                  N               C       GO
     4                                  N               D       RS
...                                   ...             ...      ...
2018 594715                             N             NaN       RJ
     594716                             N             NaN       RJ
     594717                             N             NaN       RJ
     594718                             N             NaN       RJ
     594719                             N             NaN       RJ

            UF Infração  BR Infração  Km Infração  ...  \
ano  indice                                        ...
2019 0               PR          369          132  ...
     1               RJ          356          169  ...
     2               RJ          356          169  ...
     3               GO           50          286  ...
     4               PR          116           98  ...
...                 ...          ...          ...  ...
2018 594715          RJ          101          184  ...
     594716          SP          116          110  ...
     594717          RJ          116          179  ...
     594718          RJ          101          325  ...
     594719          RJ          101          329  ...

                                  Descrição Abreviada Infração  \
ano  indice
2019 0       Transportar criança sem observância das normas...
     1       Conduzir veíc com vidro total/parcialmente cob...
     2          Conduzir o veículo com característica alterada
     3       Em movimento de dia, deixar de manter acesa lu...
     4       Deixar reduzir velocidade nas vias rurais cuja...
...                                                        ...
2018 594715  Transitar em velocidade superior à máxima perm...
     594716  Transitar em velocidade superior à máxima perm...
     594717  Transitar em velocidade superior à máxima perm...
     594718  Transitar em velocidade superior à máxima perm...
     594719  Transitar em velocidade superior à máxima perm...

             Enquadramento da Infração Início Vigência da Infração  \
ano  indice
2019 0                             168                  2016-11-01
     1                         230 XVI                  2016-11-01
     2                         230 VII                  2016-11-01
     3                         250 I b                  2016-11-01
     4                           220 V                  2016-11-01
...                                ...                         ...
2018 594715                      218 I                  2016-11-01
     594716                      218 I                  2016-11-01
     594717                      218 I                  2016-11-01
     594718                      218 I                  2016-11-01
     594719                     218 II                  2016-11-01

            Fim Vigência Infração Medição Infração Descrição Especie Veículo  \
ano  indice
2019 0                        NaN          Nenhuma                PASSAGEIRO
     1                        NaN          Nenhuma                PASSAGEIRO
     2                        NaN          Nenhuma                PASSAGEIRO
     3                        NaN          Nenhuma                     MISTO
     4                        NaN          Nenhuma                     CARGA
...                           ...              ...                       ...
2018 594715                   NaN             94.0                       NaN
     594716                   NaN            110.0                       NaN
     594717                   NaN            116.0                       NaN
     594718                   NaN             91.0                       NaN
     594719                   NaN            105.0                       NaN

            Descrição Marca Veículo Hora Infração Medição Considerada  \
ano  indice
2019 0                         FORD            18                0.00
     1                        OUTRA            16                0.00
     2                        OUTRA            16                0.00
     3                        OUTRA             9                0.00
     4                MERCEDES BENZ             3                0.00
...                             ...           ...                 ...
2018 594715                     NaN      23:58:49                87.0
     594716                     NaN      23:58:50               102.0
     594717                     NaN      23:58:57               108.0
     594718                     NaN      23:59:32                84.0
     594719                     NaN      23:59:32                98.0

            Excesso Verificado
ano  indice
2019 0                    0.00
     1                    0.00
     2                    0.00
     3                    0.00
     4                    0.00
...                        ...
2018 594715                7.0
     594716                2.0
     594717                8.0
     594718                4.0
     594719               18.0

[1113196 rows x 22 columns]

In [13]:
tabela_multa= tabela_multa.set_index('Número do Auto', append=True)
tabela_multa = tabela_multa.droplevel('indice')
tabela_multa.head()

                     Data da Infração (DD/MM/AAAA) Indicador de Abordagem  \
ano  Número do Auto
2019 5bcd39ea93ac463                    2019-01-06                      C
     e038e26abee1b3f                    2019-01-20                      C
     e4881fa47a05ae9                    2019-01-20                      C
     d6c91fa499ca5fd                    2019-01-04                      C
     8af020201f2bebf                    2019-01-04                      C

                     Assinatura do Auto Indicador Veiculo Estrangeiro  \
ano  Número do Auto
2019 5bcd39ea93ac463                  N                             S
     e038e26abee1b3f                  N                             N
     e4881fa47a05ae9                  N                             N
     d6c91fa499ca5fd                  N                             N
     8af020201f2bebf                  N                             N

                     Sentido Trafego UF Placa UF Infração  BR Infração  \
ano  Número do Auto
2019 5bcd39ea93ac463               C       -1          PR          369
     e038e26abee1b3f               D       -1          RJ          356
     e4881fa47a05ae9               D       -1          RJ          356
     d6c91fa499ca5fd               C       GO          GO           50
     8af020201f2bebf               D       RS          PR          116

                      Km Infração             Município  ...  \
ano  Número do Auto                                      ...
2019 5bcd39ea93ac463          132               IBIPORA  ...
     e038e26abee1b3f          169     SAO JOAO DA BARRA  ...
     e4881fa47a05ae9          169     SAO JOAO DA BARRA  ...
     d6c91fa499ca5fd          286               CATALAO  ...
     8af020201f2bebf           98  SAO JOSE DOS PINHAIS  ...

                                           Descrição Abreviada Infração  \
ano  Número do Auto
2019 5bcd39ea93ac463  Transportar criança sem observância das normas...
     e038e26abee1b3f  Conduzir veíc com vidro total/parcialmente cob...
     e4881fa47a05ae9     Conduzir o veículo com característica alterada
     d6c91fa499ca5fd  Em movimento de dia, deixar de manter acesa lu...
     8af020201f2bebf  Deixar reduzir velocidade nas vias rurais cuja...

                     Enquadramento da Infração Início Vigência da Infração  \
ano  Número do Auto
2019 5bcd39ea93ac463                       168                  2016-11-01
     e038e26abee1b3f                   230 XVI                  2016-11-01
     e4881fa47a05ae9                   230 VII                  2016-11-01
     d6c91fa499ca5fd                   250 I b                  2016-11-01
     8af020201f2bebf                     220 V                  2016-11-01

                     Fim Vigência Infração Medição Infração  \
ano  Número do Auto
2019 5bcd39ea93ac463                   NaN          Nenhuma
     e038e26abee1b3f                   NaN          Nenhuma
     e4881fa47a05ae9                   NaN          Nenhuma
     d6c91fa499ca5fd                   NaN          Nenhuma
     8af020201f2bebf                   NaN          Nenhuma

                     Descrição Especie Veículo Descrição Marca Veículo  \
ano  Número do Auto
2019 5bcd39ea93ac463                PASSAGEIRO                    FORD
     e038e26abee1b3f                PASSAGEIRO                   OUTRA
     e4881fa47a05ae9                PASSAGEIRO                   OUTRA
     d6c91fa499ca5fd                     MISTO                   OUTRA
     8af020201f2bebf                     CARGA           MERCEDES BENZ

                     Hora Infração Medição Considerada Excesso Verificado
ano  Número do Auto
2019 5bcd39ea93ac463            18                0.00               0.00
     e038e26abee1b3f            16                0.00               0.00
     e4881fa47a05ae9            16                0.00               0.00
     d6c91fa499ca5fd             9                0.00               0.00
     8af020201f2bebf             3                0.00               0.00

[5 rows x 21 columns]

## **Limpeza dos conjuntos de dados.**

### **Limpeza da tabela de acidentes**

In [14]:
tabela_acidentes.head()

                pesid data_inversa   dia_semana   horario  uf   br     km  \
ano  id
2019 182256.0  403856   2019-01-01  terça-feira  04:00:00  CE  116  136,9
     182263.0  402859   2019-01-01  terça-feira  05:00:00  MT  158  599,5
     182277.0  402850   2019-01-01  terça-feira  10:00:00  PA   10     34
     182289.0  402431   2019-01-01  terça-feira  08:30:00  BA  101     13
     182307.0  402638   2019-01-01  terça-feira  13:50:00  BA  116    440

                      municipio               causa_acidente  \
ano  id
2019 182256.0            RUSSAS             Animais na Pista
     182263.0          AGUA BOA  Defeito Mecânico no Veículo
     182277.0        DOM ELISEU      Velocidade Incompatível
     182289.0          RIO REAL           Ingestão de Álcool
     182307.0  FEIRA DE SANTANA           Ingestão de Álcool

                           tipo_acidente  ...       sexo ilesos feridos_leves  \
ano  id                                   ...
2019 182256.0    Atropelamento de Animal  ...  Masculino      1             0
     182263.0                   Incêndio  ...  Masculino      1             0
     182277.0           Colisão traseira  ...  Masculino      1             0
     182289.0           Colisão traseira  ...  Masculino      1             0
     182307.0  Saída de leito carroçável  ...  Masculino      0             1

              feridos_graves mortos     latitude     longitude  regional  \
ano  id
2019 182256.0              0      0    -4,766018    -38,056034   SPRF-CE
     182263.0              0      0      -14,319       -52,169   SPRF-MT
     182277.0              0      0  -4,15296734  -47,54608154   SPRF-PA
     182289.0              0      0     -11,5896      -37,8761   SPRF-SE
     182307.0              0      0      -12,344       -39,087   SPRF-BA

              delegacia             uop
ano  id
2019 182256.0  DEL03-CE  UOP01-DEL03-CE
     182263.0  DEL07-MT  UOP02-DEL07-MT
     182277.0  DEL02-PA  UOP02-DEL02-PA
     182289.0  DEL02-SE  UOP03-DEL02-SE
     182307.0  DEL02-BA  UOP01-DEL02-BA

[5 rows x 34 columns]

OBS: aqui eu pesquisei um comando que retiraria as acentuações (típicas da lingua portuguesa) dos nomes das colunas. E de resto, tirei os espaços e deixei em minúsculo.

In [15]:
tabela_acidentes.columns= tabela_acidentes.columns.str.lower().str.strip().str.replace(' ', '_')
tabela_acidentes.columns= tabela_acidentes.columns.str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [16]:
tabela_acidentes.info()

<class 'pandas.DataFrame'>
MultiIndex: 356165 entries, (np.int64(2019), np.float64(182256.0)) to (np.int64(2018), np.float64(594880.0))
Data columns (total 34 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   pesid                   356165 non-null  int64
 1   data_inversa            356165 non-null  str
 2   dia_semana              356165 non-null  str
 3   horario                 356165 non-null  str
 4   uf                      356165 non-null  str
 5   br                      356165 non-null  int64
 6   km                      356165 non-null  str
 7   municipio               356165 non-null  str
 8   causa_acidente          356165 non-null  str
 9   tipo_acidente           356078 non-null  str
 10  classificacao_acidente  356153 non-null  str
 11  fase_dia                356165 non-null  str
 12  sentido_via             356165 non-null  str
 13  condicao_metereologica  356165 non-null  str
 14  tipo_pista              356165 non-null  str
 15  tracado_via             356165 non-null  str
 16  uso_solo                356165 non-null  str
 17  id_veiculo              356165 non-null  int64
 18  tipo_veiculo            342089 non-null  str
 19  marca                   356165 non-null  str
 20  ano_fabricacao_veiculo  356165 non-null  int64
 21  tipo_envolvido          327389 non-null  str
 22  estado_fisico           327389 non-null  str
 23  idade                   356165 non-null  int64
 24  sexo                    327389 non-null  str
 25  ilesos                  356165 non-null  int64
 26  feridos_leves           356165 non-null  int64
 27  feridos_graves          356165 non-null  int64
 28  mortos                  356165 non-null  int64
 29  latitude                356165 non-null  str
 30  longitude               356165 non-null  str
 31  regional                356157 non-null  str
 32  delegacia               355961 non-null  str
 33  uop                     355936 non-null  str
dtypes: int64(9), str(25)
memory usage: 95.1 MB

#### **Separação das variáveis**

Optei por dividir a identificação das variáveis em alguns tipos

**Datas ou Horas**

In [17]:
tabela_acidentes['data_inversa']= pd.to_datetime(
                    tabela_acidentes['data_inversa'])

tabela_acidentes['horario']= pd.to_datetime(
                    tabela_acidentes['horario'], format='%H:%M:%S').dt.time #pegar só as horas pra tabela

**Categóricas**

In [18]:
#como os dias da semana são ordenados, eu uso o pd.Categorical para ordenar em gráficos futuros
ordem_dias = [
    'segunda-feira',
    'terça-feira',
    'quarta-feira',
    'quinta-feira',
    'sexta-feira',
    'sábado',
    'domingo']

tabela_acidentes['dia_semana']= pd.Categorical(
    tabela_acidentes['dia_semana'], categories=ordem_dias, ordered=True)

Categóricas com muita diversidade

In [19]:
tabela_acidentes['causa_acidente']= tabela_acidentes['causa_acidente'].astype('category') #91

Categóricas com média diversidade

In [20]:
tabela_acidentes['uf']= tabela_acidentes['uf'].astype('category') #30
tabela_acidentes['tipo_veiculo']= tabela_acidentes['tipo_veiculo'].astype('category') #25
tabela_acidentes['tipo_acidente']= tabela_acidentes['tipo_acidente'].astype('category') #21
tabela_acidentes['condicao_metereologica']= tabela_acidentes['condicao_metereologica'].astype('category') #10

Categóricas com baixa diversidade

In [21]:
tabela_acidentes['tipo_envolvido']= tabela_acidentes['tipo_envolvido'].astype('category') #5
tabela_acidentes['estado_fisico']= tabela_acidentes['estado_fisico'].astype('category') #5
tabela_acidentes['fase_dia']= tabela_acidentes['fase_dia'].astype('category') #4
tabela_acidentes['sexo']= tabela_acidentes['sexo'].astype('category') #4

In [22]:
tabela_acidentes['classificacao_acidente']= tabela_acidentes['classificacao_acidente'].astype('category') #3
tabela_acidentes['sentido_via']= tabela_acidentes['sentido_via'].astype('category') #3
tabela_acidentes['tipo_pista']= tabela_acidentes['tipo_pista'].astype('category') #3
tabela_acidentes['uso_solo']= tabela_acidentes['uso_solo'].astype('category') #2

#### **Numéricas**

Substituo as vírgulas por pontos, já que o pandas não reconhece números com vírgula como decimal

In [23]:
tabela_acidentes['km']= tabela_acidentes['km'].str.replace(',', '.')
tabela_acidentes['km']= tabela_acidentes['km'].astype('Float64')

Conferindo:

In [24]:
tabela_acidentes.info()

<class 'pandas.DataFrame'>
MultiIndex: 356165 entries, (np.int64(2019), np.float64(182256.0)) to (np.int64(2018), np.float64(594880.0))
Data columns (total 34 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   pesid                   356165 non-null  int64
 1   data_inversa            356165 non-null  datetime64[us]
 2   dia_semana              356165 non-null  category
 3   horario                 356165 non-null  object
 4   uf                      356165 non-null  category
 5   br                      356165 non-null  int64
 6   km                      356165 non-null  Float64
 7   municipio               356165 non-null  str
 8   causa_acidente          356165 non-null  category
 9   tipo_acidente           356078 non-null  category
 10  classificacao_acidente  356153 non-null  category
 11  fase_dia                356165 non-null  category
 12  sentido_via             356165 non-null  category
 13  condicao_metereologica  356165 non-null  category
 14  tipo_pista              356165 non-null  category
 15  tracado_via             356165 non-null  str
 16  uso_solo                356165 non-null  category
 17  id_veiculo              356165 non-null  int64
 18  tipo_veiculo            342089 non-null  category
 19  marca                   356165 non-null  str
 20  ano_fabricacao_veiculo  356165 non-null  int64
 21  tipo_envolvido          327389 non-null  category
 22  estado_fisico           327389 non-null  category
 23  idade                   356165 non-null  int64
 24  sexo                    327389 non-null  category
 25  ilesos                  356165 non-null  int64
 26  feridos_leves           356165 non-null  int64
 27  feridos_graves          356165 non-null  int64
 28  mortos                  356165 non-null  int64
 29  latitude                356165 non-null  str
 30  longitude               356165 non-null  str
 31  regional                356157 non-null  str
 32  delegacia               355961 non-null  str
 33  uop                     355936 non-null  str
dtypes: Float64(1), category(14), datetime64[us](1), int64(9), object(1), str(8)
memory usage: 62.2+ MB

### **Limpeza da tabela de multas**

In [25]:
tabela_multa.head()

                     Data da Infração (DD/MM/AAAA) Indicador de Abordagem  \
ano  Número do Auto
2019 5bcd39ea93ac463                    2019-01-06                      C
     e038e26abee1b3f                    2019-01-20                      C
     e4881fa47a05ae9                    2019-01-20                      C
     d6c91fa499ca5fd                    2019-01-04                      C
     8af020201f2bebf                    2019-01-04                      C

                     Assinatura do Auto Indicador Veiculo Estrangeiro  \
ano  Número do Auto
2019 5bcd39ea93ac463                  N                             S
     e038e26abee1b3f                  N                             N
     e4881fa47a05ae9                  N                             N
     d6c91fa499ca5fd                  N                             N
     8af020201f2bebf                  N                             N

                     Sentido Trafego UF Placa UF Infração  BR Infração  \
ano  Número do Auto
2019 5bcd39ea93ac463               C       -1          PR          369
     e038e26abee1b3f               D       -1          RJ          356
     e4881fa47a05ae9               D       -1          RJ          356
     d6c91fa499ca5fd               C       GO          GO           50
     8af020201f2bebf               D       RS          PR          116

                      Km Infração             Município  ...  \
ano  Número do Auto                                      ...
2019 5bcd39ea93ac463          132               IBIPORA  ...
     e038e26abee1b3f          169     SAO JOAO DA BARRA  ...
     e4881fa47a05ae9          169     SAO JOAO DA BARRA  ...
     d6c91fa499ca5fd          286               CATALAO  ...
     8af020201f2bebf           98  SAO JOSE DOS PINHAIS  ...

                                           Descrição Abreviada Infração  \
ano  Número do Auto
2019 5bcd39ea93ac463  Transportar criança sem observância das normas...
     e038e26abee1b3f  Conduzir veíc com vidro total/parcialmente cob...
     e4881fa47a05ae9     Conduzir o veículo com característica alterada
     d6c91fa499ca5fd  Em movimento de dia, deixar de manter acesa lu...
     8af020201f2bebf  Deixar reduzir velocidade nas vias rurais cuja...

                     Enquadramento da Infração Início Vigência da Infração  \
ano  Número do Auto
2019 5bcd39ea93ac463                       168                  2016-11-01
     e038e26abee1b3f                   230 XVI                  2016-11-01
     e4881fa47a05ae9                   230 VII                  2016-11-01
     d6c91fa499ca5fd                   250 I b                  2016-11-01
     8af020201f2bebf                     220 V                  2016-11-01

                     Fim Vigência Infração Medição Infração  \
ano  Número do Auto
2019 5bcd39ea93ac463                   NaN          Nenhuma
     e038e26abee1b3f                   NaN          Nenhuma
     e4881fa47a05ae9                   NaN          Nenhuma
     d6c91fa499ca5fd                   NaN          Nenhuma
     8af020201f2bebf                   NaN          Nenhuma

                     Descrição Especie Veículo Descrição Marca Veículo  \
ano  Número do Auto
2019 5bcd39ea93ac463                PASSAGEIRO                    FORD
     e038e26abee1b3f                PASSAGEIRO                   OUTRA
     e4881fa47a05ae9                PASSAGEIRO                   OUTRA
     d6c91fa499ca5fd                     MISTO                   OUTRA
     8af020201f2bebf                     CARGA           MERCEDES BENZ

                     Hora Infração Medição Considerada Excesso Verificado
ano  Número do Auto
2019 5bcd39ea93ac463            18                0.00               0.00
     e038e26abee1b3f            16                0.00               0.00
     e4881fa47a05ae9            16                0.00               0.00
     d6c91fa499ca5fd             9                0.00               0.00
     8af020201f2bebf             3                0.00               0.00

[5 rows x 21 columns]

Repito o mesmo processo nessa tabela

In [26]:
tabela_multa.columns= tabela_multa.columns.str.lower().str.strip().str.replace(' ', '_')
tabela_multa.columns= tabela_multa.columns.str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [27]:
tabela_multa.info()

<class 'pandas.DataFrame'>
MultiIndex: 1113196 entries, (np.int64(2019), '5bcd39ea93ac463') to (np.int64(2018), nan)
Data columns (total 21 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   data_da_infracao_(dd/mm/aaaa)  1113196 non-null  str
 1   indicador_de_abordagem         1113196 non-null  str
 2   assinatura_do_auto             519538 non-null   str
 3   indicador_veiculo_estrangeiro  1113196 non-null  str
 4   sentido_trafego                750985 non-null   str
 5   uf_placa                       1099424 non-null  str
 6   uf_infracao                    1113196 non-null  str
 7   br_infracao                    1113196 non-null  int64
 8   km_infracao                    1113196 non-null  int64
 9   municipio                      1113196 non-null  str
 10  codigo_da_infracao             1113196 non-null  int64
 11  descricao_abreviada_infracao   1113196 non-null  str
 12  enquadramento_da_infracao      1113196 non-null  str
 13  inicio_vigencia_da_infracao    1113196 non-null  str
 14  fim_vigencia_infracao          56 non-null       str
 15  medicao_infracao               1102347 non-null  object
 16  descricao_especie_veiculo      736297 non-null   str
 17  descricao_marca_veiculo        747857 non-null   str
 18  hora_infracao                  1113196 non-null  object
 19  medicao_considerada            1102347 non-null  object
 20  excesso_verificado             1102347 non-null  object
dtypes: int64(3), object(4), str(14)
memory usage: 187.6+ MB

#### **Separação das variáveis**

**Datas ou Horas**

In [28]:
tabela_multa['data_da_infracao_(dd/mm/aaaa)']= pd.to_datetime(
                        tabela_multa['data_da_infracao_(dd/mm/aaaa)'])

In [29]:
tabela_multa['inicio_vigencia_da_infracao']= pd.to_datetime(
        tabela_multa['inicio_vigencia_da_infracao'])

tabela_multa['fim_vigencia_infracao']= pd.to_datetime(
        tabela_multa['fim_vigencia_infracao'])

tabela_multa['hora_infracao']= pd.to_datetime(
    tabela_multa['hora_infracao'], format='mixed', errors='coerce')

**Categóricas**

In [30]:
tabela_multa['assinatura_do_auto']= tabela_multa['assinatura_do_auto'].astype('category') #3
tabela_multa['indicador_de_abordagem']= tabela_multa['indicador_de_abordagem'].astype('category') #2
tabela_multa['sentido_trafego']= tabela_multa['sentido_trafego'].astype('category') #2
tabela_multa['uf_infracao']= tabela_multa['uf_infracao'].astype('category') #27
tabela_multa['indicador_veiculo_estrangeiro']= tabela_multa['indicador_veiculo_estrangeiro'].astype('category') #2

Conferindo:

In [31]:
tabela_multa.info()

<class 'pandas.DataFrame'>
MultiIndex: 1113196 entries, (np.int64(2019), '5bcd39ea93ac463') to (np.int64(2018), nan)
Data columns (total 21 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   data_da_infracao_(dd/mm/aaaa)  1113196 non-null  datetime64[us]
 1   indicador_de_abordagem         1113196 non-null  category
 2   assinatura_do_auto             519538 non-null   category
 3   indicador_veiculo_estrangeiro  1113196 non-null  category
 4   sentido_trafego                750985 non-null   category
 5   uf_placa                       1099424 non-null  str
 6   uf_infracao                    1113196 non-null  category
 7   br_infracao                    1113196 non-null  int64
 8   km_infracao                    1113196 non-null  int64
 9   municipio                      1113196 non-null  str
 10  codigo_da_infracao             1113196 non-null  int64
 11  descricao_abreviada_infracao   1113196 non-null  str
 12  enquadramento_da_infracao      1113196 non-null  str
 13  inicio_vigencia_da_infracao    1113196 non-null  datetime64[us]
 14  fim_vigencia_infracao          56 non-null       datetime64[us]
 15  medicao_infracao               1102347 non-null  object
 16  descricao_especie_veiculo      736297 non-null   str
 17  descricao_marca_veiculo        747857 non-null   str
 18  hora_infracao                  1113196 non-null  datetime64[ns]
 19  medicao_considerada            1102347 non-null  object
 20  excesso_verificado             1102347 non-null  object
dtypes: category(5), datetime64[ns](1), datetime64[us](3), int64(3), object(3), str(6)
memory usage: 150.5+ MB

### **Decodificação das Variáveis Categóricas**

In [32]:
def substituicao(x):
    if x.strip() == 'C':
        return 'Houve abordagem'
    elif x.strip() =='S':
        return 'Não houve abordagem'

tabela_multa['indicador_de_abordagem']= tabela_multa['indicador_de_abordagem'].apply(substituicao)

In [33]:
def substituicao1(x):
    if x== 'S':
        return 'Sim'
    elif x== 'N':
        return 'Não'

tabela_multa['assinatura_do_auto']= tabela_multa['assinatura_do_auto'].apply(substituicao1)

In [34]:
def substituicao2(x):
    if x=='C':
        return 'Crescente'
    elif x== 'D':
        return 'Decrescente'

tabela_multa['sentido_trafego']= tabela_multa['sentido_trafego'].apply(substituicao2)

In [35]:
def substituicao3(x):
    if x=='S':
        return 'Sim'
    elif x=='N':
        return 'Não'

tabela_multa['indicador_veiculo_estrangeiro']= tabela_multa['indicador_veiculo_estrangeiro'].apply(substituicao3)

## **Exportação dos arquivos para `CSV`**

In [ ]:
tabela_acidentes.to_csv('tabela_acidentes_final.csv')

In [ ]:
tabela_multa.to_csv('tabela_multa_final.csv')

## **Classificação de variáveis categóricas**

`dia_semana`

A variável `dia_semana` é **qualitativa nominal**, pois representa categorias correspondentes aos dias da semana, como segunda-feira, terça-feira e quarta-feira.

Embora os dias possam ser organizados em uma sequência cronológica, essa sequência não representa uma hierarquia ou uma ordem de grandeza entre as categorias. Não é possível afirmar que segunda-feira é maior ou menor que terça-feira.

`fase_dia`

A variável `fase_dia` é **qualitativa ordinal**, pois representa categorias relacionadas ao momento do dia, como `Pleno dia`, `Anoitecer` e `Plena noite`.

Essas categorias podem ser organizadas em uma sequência relacionada a luminosidade e a progressão do horário do dia. Entretanto, não existe uma distância numérica definida entre elas.

Essa variável pode ser armazenada como texto ou categoria, mas pode receber uma ordem específica. Por exemplo, no Pandas, seria possível definir uma ordem entre as categorias para facilitar análises e gráficos.

`idade`

A variável `idade` é **quantitativa contínua**, pois representa uma medida numérica que pode, em sua natureza, assumir qualquer valor dentro de um intervalo.

Por exemplo, uma pessoa pode ter 17 anos, 17,5 anos ou 17 anos e 3 meses. Mesmo quando a idade é registrada no dataset apenas em anos completos, a variável continua sendo naturalmente contínua.

`veiculos`

A variável `veiculos` é **quantitativa discreta**, pois representa uma contagem da quantidade de veículos envolvidos em uma ocorrência.

Ela pode assumir valores inteiros, como 1, 2, 3 ou 4 veículos, mas não valores intermediários. Por exemplo, não é possível existir 2,5 veículos envolvidos em um acidente.

## **Codificação das varáveis categóricas**

Para substituir os valores categóricos de `fase_dia`, eu optei por usar uma função e através dessa função usar a função de mapeamento `apply`. Respeitando a gradação da luz do dia.

In [38]:
def substituicao(x):
    if x== 'Amanhecer':
        return 1
    elif x== 'Pleno dia':
        return 2
    elif x== 'Anoitecer':
        return 3
    elif x== 'Plena noite':
        return 4
    elif not x:
        return None

tabela_acidentes['fase_dia']= tabela_acidentes['fase_dia'].apply(substituicao)

In [39]:
dicionario= {'Amanhecer': 1, 'Pleno dia': 2, 'Anoitecer': 3, 'Plena Noite': 4}
dicionario= pd.DataFrame(dicionario, index=[1])
dicionario

   Amanhecer  Pleno dia  Anoitecer  Plena Noite
1          1          2          3            4

In [40]:
tabela_acidentes.head(5)

                pesid data_inversa   dia_semana   horario  uf   br     km  \
ano  id
2019 182256.0  403856   2019-01-01  terça-feira  04:00:00  CE  116  136.9
     182263.0  402859   2019-01-01  terça-feira  05:00:00  MT  158  599.5
     182277.0  402850   2019-01-01  terça-feira  10:00:00  PA   10   34.0
     182289.0  402431   2019-01-01  terça-feira  08:30:00  BA  101   13.0
     182307.0  402638   2019-01-01  terça-feira  13:50:00  BA  116  440.0

                      municipio               causa_acidente  \
ano  id
2019 182256.0            RUSSAS             Animais na Pista
     182263.0          AGUA BOA  Defeito Mecânico no Veículo
     182277.0        DOM ELISEU      Velocidade Incompatível
     182289.0          RIO REAL           Ingestão de Álcool
     182307.0  FEIRA DE SANTANA           Ingestão de Álcool

                           tipo_acidente  ...       sexo  ilesos  \
ano  id                                   ...
2019 182256.0    Atropelamento de Animal  ...  Masculino       1
     182263.0                   Incêndio  ...  Masculino       1
     182277.0           Colisão traseira  ...  Masculino       1
     182289.0           Colisão traseira  ...  Masculino       1
     182307.0  Saída de leito carroçável  ...  Masculino       0

              feridos_leves feridos_graves mortos     latitude     longitude  \
ano  id
2019 182256.0             0              0      0    -4,766018    -38,056034
     182263.0             0              0      0      -14,319       -52,169
     182277.0             0              0      0  -4,15296734  -47,54608154
     182289.0             0              0      0     -11,5896      -37,8761
     182307.0             1              0      0      -12,344       -39,087

               regional delegacia             uop
ano  id
2019 182256.0   SPRF-CE  DEL03-CE  UOP01-DEL03-CE
     182263.0   SPRF-MT  DEL07-MT  UOP02-DEL07-MT
     182277.0   SPRF-PA  DEL02-PA  UOP02-DEL02-PA
     182289.0   SPRF-SE  DEL02-SE  UOP03-DEL02-SE
     182307.0   SPRF-BA  DEL02-BA  UOP01-DEL02-BA

[5 rows x 34 columns]

## **Categorização da coluna `idade`**

Apliquei o mesmo principio da tarefa anterior, usando funções e mapeamentos.

In [41]:
def substituicao(x):
    if 0<=x<18:
        return 'Menores de Idade'
    elif 18<=x<30:
        return 'Jovens'
    elif 30<=x<60:
        return 'Adultos'
    elif 60<=x<120:
        return 'Idosos'

tabela_acidentes['faixa_etaria']= tabela_acidentes['idade'].apply(substituicao)

## **Frequencia das variáveis categóricas**

In [42]:
fi= tabela_acidentes['faixa_etaria'].value_counts()
fr= (tabela_acidentes['faixa_etaria'].value_counts(normalize=True)*100)
Fi= fi.cumsum()
Fr= fr.cumsum()
total= tabela_acidentes['faixa_etaria'].value_counts().sum()

In [44]:
tabela= pd.DataFrame(
    {'fi': fi, 'fr(%)': fr, 'Fi': Fi, 'Fr(%)': Fr},
    index=['Adultos', 'Jovens', 'Menores de Idade', 'Idosos']
)

total= pd.DataFrame({
    'fi': fi.sum(),
    'fr(%)': fr.sum(),
    'Fi': '-',
    'Fr(%)': '-' 
}, index=['Total'])

tabela_comparacao = pd.concat([tabela, total])
tabela_comparacao

                      fi       fr(%)      Fi      Fr(%)
Adultos           175755   49.416578  175755  49.416578
Jovens             76743   21.577630  252498  70.994208
Menores de Idade   75062   21.104988  327560  92.099196
Idosos             28100    7.900804  355660      100.0
Total             355660  100.000000       -          -

## **Resposta às perguntas:**

Os adultos de **18 a 30 anos** são os mais envolvidos em acidentes, com **701.628 registros** nessa faixa etária.

Em relação à proporção de pessoas com menos de 60 anos, considerando todas as categorias anteriores à faixa dos idosos, elas representam **91,7%** do total de pessoas envolvidas em acidentes.

A **frequência acumulada** pode ser utilizada para responder perguntas que envolvem critérios de inclusão ou exclusão de faixas etárias, como:

* Quantos acidentados tinham **até 50 anos**?
* Quantos acidentados tinham **pelo menos 50 anos**?

Essas informações podem ajudar a identificar as faixas etárias mais vulneráveis e direcionar esforços de conscientização e prevenção para os grupos com maior participação nas ocorrências.