# **Projeto de Estatística: Análise Exploratória de Dados da PRF**

Análise e exploração de dados da Polícia Rodoviária Federal para identificar padrões e características presentes nos dados de acidentes e multas.

In [439]:
#Importação da biblioteca Pandas como pd
import pandas as pd

#Importação da biblioteca Numpy para operações matemáticas
import numpy as np

**Aluno: Thales Trajano Farias**

**Dataset utilizado: `Acidentes (agrupados por pessoas)` e `Multas` ano de 2018-2025**

## **Importação dos DataFrames**

OBS: Optei por colocar todos os arquivos em variáveis, e todos em uma única célula, para facilitar caso haja mudança futura no caminho dos arquivos.

In [1]:
acidentes1= 'Acidentes/acidentes2025.csv'
acidentes2= 'Acidentes/acidentes2024.csv'
acidentes3='Acidentes/acidentes2023.csv'
acidentes4= 'Acidentes/acidentes2022.csv'
acidentes5= 'Acidentes/acidentes2021.csv'
acidentes6= 'Acidentes/acidentes2020.csv'
acidentes7='Acidentes/acidentes2019.csv'
acidentes8='Acidentes/acidentes2018.csv'

Eu optei por escolher os acidentes agrupados por ocorrência. Nesse  caso a maioria dos arquivos eram separados por ponto e vírgula e tinham codificação diferente da padrão `UTF-8`, eles usavam o `latin1`

In [ ]:
df1= pd.read_csv(acidentes1,
                sep=';',
                encoding='latin1')

In [ ]:
df2= pd.read_csv(acidentes2,
                sep=';',
                encoding='latin1')

In [ ]:
df3= pd.read_csv(acidentes3,
                sep=';',
                encoding='latin1')

In [ ]:
df4= pd.read_csv(acidentes4,
                sep=';',
                encoding='latin1')

In [ ]:
df5= pd.read_csv(acidentes5,
                sep=';',
                encoding='latin1')

In [ ]:
df6= pd.read_csv(acidentes6,
                sep=';',
                encoding='latin1')

In [ ]:
df7= pd.read_csv(acidentes7,
                sep=';',
                encoding='latin1')

In [ ]:
df8= pd.read_csv(acidentes8,
                sep=';',
                encoding='latin1')

## **Importação dos arquivos de multa**

OBS: Fiz a mesma coisa que na importação passada e coloquei todos em variáveis e na mesma célula para facilitar caso haja mudança no caminho do arquivo.

In [ ]:
multa1= 'Infrações.2018-2025/infraçoes2025_01.csv'
multa2= 'Infrações.2018-2025/infraçoes2024_01.csv'
multa3= 'Infrações.2018-2025/infraçoes2023_01.csv'
multa4= 'Infrações.2018-2025/infraçoes2022_01.csv'
multa5= 'Infrações.2018-2025/infraçoes2021_01.csv'
multa6= 'Infrações.2018-2025/infraçoes2020_01.csv'
multa7= 'Infrações.2018-2025/infraçoes2019_01.csv'
multa8= 'Infrações.2018-2025/infraçoes2018_01.csv'

In [ ]:
t1= pd.read_csv(multa1, 
                sep=';', 
                encoding='latin1', 
                )

Alguns arquivos estavam dando erro porque o `Pandas` identificava uma coluna com um tipo de valor e depois se deparava com outro valor diferente, então tava dando um aviso de erro mesmo que a tabela rodasse. Para evitar esse aviso, botei o argumento `low_memory=False`

In [ ]:
t2= pd.read_csv(multa2, 
                sep=';', 
                encoding='latin1', 
                low_memory=False 
                )

In [ ]:
t3= pd.read_csv(multa3, 
                sep=';', 
                encoding='latin1', 
                low_memory=False
                )

In [ ]:
t4= pd.read_csv(multa4, 
                sep=';', 
                encoding='latin1', 
                low_memory=False
                )

In [ ]:
t5= pd.read_csv(multa5, 
                sep=';', 
                encoding='latin1', 
                low_memory=False
                )

In [ ]:
t6= pd.read_csv(multa6, 
                sep=';', 
                encoding='latin1', 
                low_memory=False
                )

In [ ]:
t7= pd.read_csv(multa7, 
                sep=';', 
                encoding='utf-8', 
                low_memory=False
                )

In [ ]:
t8= pd.read_csv(multa8, 
                sep=',', 
                encoding='latin1', 
                low_memory=False
                )

## **Comparação entre as tabelas de Multas e Acidentes**

Apesar de possuírem objetivos diferentes, as tabelas **Multas** e **Acidentes** apresentam algumas colunas com informações semelhantes.

### Informações em comum

- Ambas possuem uma coluna de **data**, no formato `dd/mm/aaaa`.
- Possuem informações para identificar o **local da ocorrência**, como:
  - **BR**
  - **KM da BR**
- Ambas informam o **município** onde ocorreu o acidente ou a infração.
- Também possuem a **Unidade Federativa (UF)** correspondente à ocorrência.

### Informações específicas

Embora existam semelhanças entre algumas variáveis, cada tabela possui colunas específicas relacionadas ao seu objetivo.

Na tabela de **Acidentes**, são utilizadas colunas como:

- `causa_acidente`
- `tipo_acidente`
- Quantidade de feridos, incluindo:
  - Feridos leves
  - Feridos graves
  - Feridos ignorados
  - Mortos
- Tipo da pista
- Condição meteorológica
- Outras informações relacionadas às características e consequências do acidente.

Já a tabela de **Multas** possui informações relacionadas à fiscalização e às infrações de trânsito, como:

- Informações sobre a abordagem do veículo
- Sentido do tráfego
- Data de início e fim da vigência
- Medição realizada
- `descricao_abreviada`, utilizada para identificar a infração cometida
- Outras informações específicas relacionadas à aplicação das multas.

Embora as duas tabelas compartilhem informações relacionadas ao **tempo e ao local das ocorrências**, suas demais variáveis são voltadas para objetivos distintos: a tabela **Acidentes** apresenta informações sobre ocorrências e suas consequências, enquanto a tabela **Multas** está relacionada à fiscalização e às infrações de trânsito.

## **Concatenação das tabelas**

### **Concatenação das tabelas de acidentes**

A tabela de acidentes já possui colunas com os mesmos nomes em todos os anos, de 2018 até 2025. Então bastou concatenar com o argumento `keys` para criar os multiindex referentes a cada ano.

In [ ]:
tabela_acidentes= pd.concat([df1, df2, df3, df4, df5, df6, df7, df8],
                            keys=[2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018],
                           names=['ano', 'indice'])

In [ ]:
tabela_acidentes= tabela_acidentes.set_index('id', append=True)
tabela_acidentes = tabela_acidentes.droplevel('indice')
tabela_acidentes.head()

                 pesid data_inversa    dia_semana   horario  uf   br     km  \
ano  id
2025 652493.0  1467686   2025-01-01  quarta-feira  06:20:00  SP  116    225
     652519.0  1467833   2025-01-01  quarta-feira  07:50:00  CE  116  546,2
     652522.0  1468042   2025-01-01  quarta-feira  08:45:00  PR  369   88,2
     652544.0  1467849   2025-01-01  quarta-feira  11:00:00  PR  116     74
     652549.0  1467791   2025-01-01  quarta-feira  09:30:00  MG  251    471

                           municipio  \
ano  id
2025 652493.0              GUARULHOS
     652519.0              PENAFORTE
     652522.0      CORNELIO PROCOPIO
     652544.0  CAMPINA GRANDE DO SUL
     652549.0           FRANCISCO SA

                                         causa_acidente  \
ano  id
2025 652493.0  Reação tardia ou ineficiente do condutor
     652519.0                          Pista esburacada
     652522.0  Reação tardia ou ineficiente do condutor
     652544.0  Reação tardia ou ineficiente do condutor
     652549.0                   Velocidade Incompatível

                           tipo_acidente  ...           sexo ilesos  \
ano  id                                   ...
2025 652493.0                 Tombamento  ...  Não Informado      0
     652519.0            Colisão frontal  ...      Masculino      1
     652522.0           Colisão traseira  ...      Masculino      1
     652544.0  Saída de leito carroçável  ...      Masculino      1
     652549.0            Colisão frontal  ...      Masculino      1

              feridos_leves feridos_graves mortos      latitude     longitude  \
ano  id
2025 652493.0             0              0      0  -23,48586772  -46,54075317
     652519.0             0              0      0     -7,812288  -39,08333306
     652522.0             0              0      0    -23,182565    -50,637228
     652544.0             0              0      0  -25,36517687  -49,04223028
     652549.0             0              0      0  -16,46801304  -43,43121303

               regional delegacia             uop
ano  id
2025 652493.0   SPRF-SP  DEL01-SP  UOP01-DEL01-SP
     652519.0   SPRF-CE  DEL05-CE  UOP03-DEL05-CE
     652522.0   SPRF-PR  DEL07-PR  UOP05-DEL07-PR
     652544.0   SPRF-PR  DEL01-PR  UOP02-DEL01-PR
     652549.0   SPRF-MG  DEL12-MG  UOP01-DEL12-MG

[5 rows x 34 columns]

### **Concatenação das tabelas de multas**

A tabela de multas começou com 22 colunas até 2021, em 2022 foi para 25 colunas. Em 2018, no entanto, as colunas tinham nomes diferentes, embora significados iguais, então eu uso o comando `rename` para mudar o nome das colunas de 2018 para seus equivalentes nos anos seguintes

In [ ]:
t8 = t8.rename(
    columns={
        'dat_infracao': 'Data da Infração (DD/MM/AAAA)',
        'hora': 'Hora Infração',
        'tip_abordagem': 'Indicador de Abordagem',
        'ind_assinou_auto': 'Assinatura do Auto',
        'ind_veiculo_estrangeiro': 'Indicador Veiculo Estrangeiro',
        'ind_sentido_trafego': 'Sentido Trafego',
        'uf_placa': 'UF Placa',
        'uf_infracao': 'UF Infração',
        'num_br_infracao': 'BR Infração',
        'num_km_infracao': 'Km Infração',
        'nom_municipio': 'Município',
        'cod_infracao': 'Código da Infração',
        'descricao_abreviada': 'Descrição Abreviada Infração',
        'enquadramento': 'Enquadramento da Infração',
        'data_inicio_vigencia': 'Início Vigência da Infração',
        'data_fim_vigencia': 'Fim Vigência Infração',
        'med_realizada': 'Medição Infração',
        'med_considerada': 'Medição Considerada',
        'exc_verificado': 'Excesso Verificado',
        'especie': 'Descrição Especie Veículo',
        'nome_veiculo_marca': 'Descrição Marca Veículo'
    }
)

OBS: como a coluna `nom_modelo_veiculo` só existe na tabela de 2018 e em nenhuma outra dos anos seguintes, eu tirei para evitar uma coluna que praticamente só teria valores `Nan`.

In [ ]:
t8= t8.drop(columns=['nom_modelo_veiculo'])

In [ ]:
tabela_multa= pd.concat([t1, t2, t3, t4, t5, t6, t7, t8],
                        keys=[2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018],
                        names=['ano', 'indice'])

In [ ]:
tabela_multa= tabela_multa.set_index('Número do Auto', append=True)
tabela_multa = tabela_multa.droplevel('indice')
tabela_multa.head()

                     Data da Infração (DD/MM/AAAA) Indicador de Abordagem  \
ano  Número do Auto
2025 6bf84970d11e700                    2025-01-03                      S
     b2bddb1ca8eee2e                    2025-01-03                      S
     3ed86bee5a764d3                    2025-01-03                      S
     29c4121822be0cf                    2025-01-13                      S
     99e930f7bf4c8bb                    2025-01-13                      S

                     Assinatura do Auto Sentido Trafego UF Infração  \
ano  Número do Auto
2025 6bf84970d11e700                  N               D          SC
     b2bddb1ca8eee2e                  N               D          SC
     3ed86bee5a764d3                  N               D          SC
     29c4121822be0cf                  N               C          MG
     99e930f7bf4c8bb                  N               D          MG

                      BR Infração  Km Infração             Município  \
ano  Número do Auto
2025 6bf84970d11e700          101          187               BIGUACU
     b2bddb1ca8eee2e          101          188               BIGUACU
     3ed86bee5a764d3          101          211               PALHOCA
     29c4121822be0cf           40          637  CONSELHEIRO LAFAIETE
     99e930f7bf4c8bb           40          637  CONSELHEIRO LAFAIETE

                     Indicador Veiculo Estrangeiro UF Placa  ...  \
ano  Número do Auto                                          ...
2025 6bf84970d11e700                             N       SC  ...
     b2bddb1ca8eee2e                             N       SC  ...
     3ed86bee5a764d3                             N       SC  ...
     29c4121822be0cf                             N       MG  ...
     99e930f7bf4c8bb                             N       MG  ...

                     Código da Infração  \
ano  Número do Auto
2025 6bf84970d11e700              58600
     b2bddb1ca8eee2e              57703
     3ed86bee5a764d3              58000
     29c4121822be0cf              68401
     99e930f7bf4c8bb              68401

                                           Descrição Abreviada Infração  \
ano  Número do Auto
2025 6bf84970d11e700  Deixar de dar passagem pela esquerda quando so...
     b2bddb1ca8eee2e  Deixar de dar passagem a veíc de polícia em se...
     3ed86bee5a764d3  Deixar guardar dist segurança lat/front entre ...
     29c4121822be0cf  Transitar em desacordo c/ autorização expedida...
     99e930f7bf4c8bb  Transitar em desacordo c/ autorização expedida...

                     Enquadramento da Infração Início Vigência da Infração  \
ano  Número do Auto
2025 6bf84970d11e700                       198                  2016-11-01
     b2bddb1ca8eee2e                       189                  2016-11-01
     3ed86bee5a764d3                       192                  2016-11-01
     29c4121822be0cf                    231 VI                  2016-11-01
     99e930f7bf4c8bb                    231 VI                  2016-11-01

                      Fim Vigência Infração Medição Infração Hora Infração  \
ano  Número do Auto
2025 6bf84970d11e700                    NaN          Nenhuma            15
     b2bddb1ca8eee2e                    NaN          Nenhuma            15
     3ed86bee5a764d3                    NaN          Nenhuma            15
     29c4121822be0cf                    NaN          Nenhuma            10
     99e930f7bf4c8bb                    NaN          Nenhuma            10

                     Medição Considerada Excesso Verificado Qtd Infrações
ano  Número do Auto
2025 6bf84970d11e700                 0.0                0.0           1.0
     b2bddb1ca8eee2e                 0.0                0.0           1.0
     3ed86bee5a764d3                 0.0                0.0           1.0
     29c4121822be0cf                 0.0                0.0           1.0
     99e930f7bf4c8bb                 0.0                0.0           1.0

[5 rows x 24 columns]

## **Limpeza dos conjuntos de dados.**

### **Limpeza da tabela de acidentes**

In [ ]:
tabela_acidentes.head()

                 pesid data_inversa    dia_semana   horario  uf   br     km  \
ano  id
2025 652493.0  1467686   2025-01-01  quarta-feira  06:20:00  SP  116    225
     652519.0  1467833   2025-01-01  quarta-feira  07:50:00  CE  116  546,2
     652522.0  1468042   2025-01-01  quarta-feira  08:45:00  PR  369   88,2
     652544.0  1467849   2025-01-01  quarta-feira  11:00:00  PR  116     74
     652549.0  1467791   2025-01-01  quarta-feira  09:30:00  MG  251    471

                           municipio  \
ano  id
2025 652493.0              GUARULHOS
     652519.0              PENAFORTE
     652522.0      CORNELIO PROCOPIO
     652544.0  CAMPINA GRANDE DO SUL
     652549.0           FRANCISCO SA

                                         causa_acidente  \
ano  id
2025 652493.0  Reação tardia ou ineficiente do condutor
     652519.0                          Pista esburacada
     652522.0  Reação tardia ou ineficiente do condutor
     652544.0  Reação tardia ou ineficiente do condutor
     652549.0                   Velocidade Incompatível

                           tipo_acidente  ...           sexo ilesos  \
ano  id                                   ...
2025 652493.0                 Tombamento  ...  Não Informado      0
     652519.0            Colisão frontal  ...      Masculino      1
     652522.0           Colisão traseira  ...      Masculino      1
     652544.0  Saída de leito carroçável  ...      Masculino      1
     652549.0            Colisão frontal  ...      Masculino      1

              feridos_leves feridos_graves mortos      latitude     longitude  \
ano  id
2025 652493.0             0              0      0  -23,48586772  -46,54075317
     652519.0             0              0      0     -7,812288  -39,08333306
     652522.0             0              0      0    -23,182565    -50,637228
     652544.0             0              0      0  -25,36517687  -49,04223028
     652549.0             0              0      0  -16,46801304  -43,43121303

               regional delegacia             uop
ano  id
2025 652493.0   SPRF-SP  DEL01-SP  UOP01-DEL01-SP
     652519.0   SPRF-CE  DEL05-CE  UOP03-DEL05-CE
     652522.0   SPRF-PR  DEL07-PR  UOP05-DEL07-PR
     652544.0   SPRF-PR  DEL01-PR  UOP02-DEL01-PR
     652549.0   SPRF-MG  DEL12-MG  UOP01-DEL12-MG

[5 rows x 34 columns]

OBS: aqui eu pesquisei um comando que retiraria as acentuações (típicas da lingua portuguesa) dos nomes das colunas. E de resto, tirei os espaços e deixei em minúsculo.

In [ ]:
tabela_acidentes.columns= tabela_acidentes.columns.str.lower().str.strip().str.replace(' ', '_')
tabela_acidentes.columns= tabela_acidentes.columns.str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [ ]:
tabela_acidentes.info()

<class 'pandas.DataFrame'>
MultiIndex: 1429818 entries, (np.int64(2025), np.float64(652493.0)) to (np.int64(2018), np.float64(594880.0))
Data columns (total 34 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   pesid                   1429818 non-null  int64
 1   data_inversa            1429818 non-null  str
 2   dia_semana              1429818 non-null  str
 3   horario                 1429818 non-null  str
 4   uf                      1429818 non-null  str
 5   br                      1429818 non-null  int64
 6   km                      1429818 non-null  str
 7   municipio               1429818 non-null  str
 8   causa_acidente          1429818 non-null  str
 9   tipo_acidente           1429730 non-null  str
 10  classificacao_acidente  1429779 non-null  str
 11  fase_dia                1429818 non-null  str
 12  sentido_via             1429818 non-null  str
 13  condicao_metereologica  1429818 non-null  str
 14  tipo_pista              1429818 non-null  str
 15  tracado_via             1429818 non-null  str
 16  uso_solo                1429818 non-null  str
 17  id_veiculo              1429818 non-null  int64
 18  tipo_veiculo            1376936 non-null  str
 19  marca                   1429818 non-null  str
 20  ano_fabricacao_veiculo  1429818 non-null  int64
 21  tipo_envolvido          1305032 non-null  str
 22  estado_fisico           1305032 non-null  str
 23  idade                   1429818 non-null  int64
 24  sexo                    1305032 non-null  str
 25  ilesos                  1429818 non-null  int64
 26  feridos_leves           1429818 non-null  int64
 27  feridos_graves          1429818 non-null  int64
 28  mortos                  1429818 non-null  int64
 29  latitude                1429818 non-null  object
 30  longitude               1429818 non-null  object
 31  regional                1429708 non-null  str
 32  delegacia               1429157 non-null  str
 33  uop                     1428540 non-null  str
dtypes: int64(9), object(2), str(23)
memory usage: 381.9+ MB

#### **Separação das variáveis**

Optei por dividir a identificação das variáveis em alguns tipos

**Datas ou Horas**

In [ ]:
tabela_acidentes['data_inversa']= pd.to_datetime(
                    tabela_acidentes['data_inversa'])

tabela_acidentes['horario']= pd.to_datetime(
                    tabela_acidentes['horario'], format='%H:%M:%S').dt.time #pegar só as horas pra tabela

**Categóricas**

In [ ]:
#como os dias da semana são ordenados, eu uso o pd.Categorical para ordenar em gráficos futuros
ordem_dias = [
    'segunda-feira',
    'terça-feira',
    'quarta-feira',
    'quinta-feira',
    'sexta-feira',
    'sábado',
    'domingo']

tabela_acidentes['dia_semana']= pd.Categorical(
    tabela_acidentes['dia_semana'], categories=ordem_dias, ordered=True)

Categóricas com muita diversidade

In [ ]:
tabela_acidentes['causa_acidente']= tabela_acidentes['causa_acidente'].astype('category') #91

Categóricas com média diversidade

In [ ]:
tabela_acidentes['uf']= tabela_acidentes['uf'].astype('category') #30
tabela_acidentes['tipo_veiculo']= tabela_acidentes['tipo_veiculo'].astype('category') #25
tabela_acidentes['tipo_acidente']= tabela_acidentes['tipo_acidente'].astype('category') #21
tabela_acidentes['condicao_metereologica']= tabela_acidentes['condicao_metereologica'].astype('category') #10

Categóricas com baixa diversidade

In [ ]:
tabela_acidentes['tipo_envolvido']= tabela_acidentes['tipo_envolvido'].astype('category') #5
tabela_acidentes['estado_fisico']= tabela_acidentes['estado_fisico'].astype('category') #5
tabela_acidentes['fase_dia']= tabela_acidentes['fase_dia'].astype('category') #4
tabela_acidentes['sexo']= tabela_acidentes['sexo'].astype('category') #4

In [ ]:
tabela_acidentes['classificacao_acidente']= tabela_acidentes['classificacao_acidente'].astype('category') #3
tabela_acidentes['sentido_via']= tabela_acidentes['sentido_via'].astype('category') #3
tabela_acidentes['tipo_pista']= tabela_acidentes['tipo_pista'].astype('category') #3
tabela_acidentes['uso_solo']= tabela_acidentes['uso_solo'].astype('category') #2

#### **Numéricas**

Substituo as vírgulas por pontos, já que o pandas não reconhece números com vírgula como decimal

In [ ]:
tabela_acidentes['km']= tabela_acidentes['km'].str.replace(',', '.')
tabela_acidentes['km']= tabela_acidentes['km'].astype('Float64')

In [ ]:
tabela_acidentes.info()

<class 'pandas.DataFrame'>
MultiIndex: 1429818 entries, (np.int64(2025), np.float64(652493.0)) to (np.int64(2018), np.float64(594880.0))
Data columns (total 34 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   pesid                   1429818 non-null  int64
 1   data_inversa            1429818 non-null  datetime64[us]
 2   dia_semana              1429818 non-null  category
 3   horario                 1429818 non-null  object
 4   uf                      1429818 non-null  category
 5   br                      1429818 non-null  int64
 6   km                      1429818 non-null  Float64
 7   municipio               1429818 non-null  str
 8   causa_acidente          1429818 non-null  category
 9   tipo_acidente           1429730 non-null  category
 10  classificacao_acidente  1429779 non-null  category
 11  fase_dia                1429818 non-null  category
 12  sentido_via             1429818 non-null  category
 13  condicao_metereologica  1429818 non-null  category
 14  tipo_pista              1429818 non-null  category
 15  tracado_via             1429818 non-null  str
 16  uso_solo                1429818 non-null  category
 17  id_veiculo              1429818 non-null  int64
 18  tipo_veiculo            1376936 non-null  category
 19  marca                   1429818 non-null  str
 20  ano_fabricacao_veiculo  1429818 non-null  int64
 21  tipo_envolvido          1305032 non-null  category
 22  estado_fisico           1305032 non-null  category
 23  idade                   1429818 non-null  int64
 24  sexo                    1305032 non-null  category
 25  ilesos                  1429818 non-null  int64
 26  feridos_leves           1429818 non-null  int64
 27  feridos_graves          1429818 non-null  int64
 28  mortos                  1429818 non-null  int64
 29  latitude                1429818 non-null  object
 30  longitude               1429818 non-null  object
 31  regional                1429708 non-null  str
 32  delegacia               1429157 non-null  str
 33  uop                     1428540 non-null  str
dtypes: Float64(1), category(14), datetime64[us](1), int64(9), object(3), str(6)
memory usage: 249.6+ MB

### **Limpeza da tabela de multas**

In [ ]:
tabela_multa.head()

                     Data da Infração (DD/MM/AAAA) Indicador de Abordagem  \
ano  Número do Auto
2025 6bf84970d11e700                    2025-01-03                      S
     b2bddb1ca8eee2e                    2025-01-03                      S
     3ed86bee5a764d3                    2025-01-03                      S
     29c4121822be0cf                    2025-01-13                      S
     99e930f7bf4c8bb                    2025-01-13                      S

                     Assinatura do Auto Sentido Trafego UF Infração  \
ano  Número do Auto
2025 6bf84970d11e700                  N               D          SC
     b2bddb1ca8eee2e                  N               D          SC
     3ed86bee5a764d3                  N               D          SC
     29c4121822be0cf                  N               C          MG
     99e930f7bf4c8bb                  N               D          MG

                      BR Infração  Km Infração             Município  \
ano  Número do Auto
2025 6bf84970d11e700          101          187               BIGUACU
     b2bddb1ca8eee2e          101          188               BIGUACU
     3ed86bee5a764d3          101          211               PALHOCA
     29c4121822be0cf           40          637  CONSELHEIRO LAFAIETE
     99e930f7bf4c8bb           40          637  CONSELHEIRO LAFAIETE

                     Indicador Veiculo Estrangeiro UF Placa  ...  \
ano  Número do Auto                                          ...
2025 6bf84970d11e700                             N       SC  ...
     b2bddb1ca8eee2e                             N       SC  ...
     3ed86bee5a764d3                             N       SC  ...
     29c4121822be0cf                             N       MG  ...
     99e930f7bf4c8bb                             N       MG  ...

                     Código da Infração  \
ano  Número do Auto
2025 6bf84970d11e700              58600
     b2bddb1ca8eee2e              57703
     3ed86bee5a764d3              58000
     29c4121822be0cf              68401
     99e930f7bf4c8bb              68401

                                           Descrição Abreviada Infração  \
ano  Número do Auto
2025 6bf84970d11e700  Deixar de dar passagem pela esquerda quando so...
     b2bddb1ca8eee2e  Deixar de dar passagem a veíc de polícia em se...
     3ed86bee5a764d3  Deixar guardar dist segurança lat/front entre ...
     29c4121822be0cf  Transitar em desacordo c/ autorização expedida...
     99e930f7bf4c8bb  Transitar em desacordo c/ autorização expedida...

                     Enquadramento da Infração Início Vigência da Infração  \
ano  Número do Auto
2025 6bf84970d11e700                       198                  2016-11-01
     b2bddb1ca8eee2e                       189                  2016-11-01
     3ed86bee5a764d3                       192                  2016-11-01
     29c4121822be0cf                    231 VI                  2016-11-01
     99e930f7bf4c8bb                    231 VI                  2016-11-01

                      Fim Vigência Infração Medição Infração Hora Infração  \
ano  Número do Auto
2025 6bf84970d11e700                    NaN          Nenhuma            15
     b2bddb1ca8eee2e                    NaN          Nenhuma            15
     3ed86bee5a764d3                    NaN          Nenhuma            15
     29c4121822be0cf                    NaN          Nenhuma            10
     99e930f7bf4c8bb                    NaN          Nenhuma            10

                     Medição Considerada Excesso Verificado Qtd Infrações
ano  Número do Auto
2025 6bf84970d11e700                 0.0                0.0           1.0
     b2bddb1ca8eee2e                 0.0                0.0           1.0
     3ed86bee5a764d3                 0.0                0.0           1.0
     29c4121822be0cf                 0.0                0.0           1.0
     99e930f7bf4c8bb                 0.0                0.0           1.0

[5 rows x 24 columns]

Repito o mesmo processo nessa tabela

In [ ]:
tabela_multa.columns= tabela_multa.columns.str.lower().str.strip().str.replace(' ', '_')
tabela_multa.columns= tabela_multa.columns.str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [ ]:
tabela_multa.info()

<class 'pandas.DataFrame'>
MultiIndex: 4285542 entries, (np.int64(2025), '6bf84970d11e700') to (np.int64(2018), nan)
Data columns (total 24 columns):
 #   Column                         Dtype
---  ------                         -----
 0   data_da_infracao_(dd/mm/aaaa)  str
 1   indicador_de_abordagem         str
 2   assinatura_do_auto             str
 3   sentido_trafego                str
 4   uf_infracao                    str
 5   br_infracao                    int64
 6   km_infracao                    int64
 7   municipio                      str
 8   indicador_veiculo_estrangeiro  str
 9   uf_placa                       str
 10  descricao_especie_veiculo      str
 11  descricao_marca_veiculo        str
 12  descricao_tipo_veiculo         str
 13  descricao_modelo_veiculo       str
 14  codigo_da_infracao             int64
 15  descricao_abreviada_infracao   str
 16  enquadramento_da_infracao      str
 17  inicio_vigencia_da_infracao    str
 18  fim_vigencia_infracao          object
 19  medicao_infracao               object
 20  hora_infracao                  object
 21  medicao_considerada            object
 22  excesso_verificado             object
 23  qtd_infracoes                  float64
dtypes: float64(1), int64(3), object(5), str(15)
memory usage: 833.3+ MB

#### **Separação das variáveis**

**Datas ou Horas**

In [ ]:
tabela_multa['data_da_infracao_(dd/mm/aaaa)']= pd.to_datetime(
                        tabela_multa['data_da_infracao_(dd/mm/aaaa)'])

In [ ]:
tabela_multa['inicio_vigencia_da_infracao']= pd.to_datetime(
        tabela_multa['inicio_vigencia_da_infracao'])

tabela_multa['fim_vigencia_infracao']= pd.to_datetime(
        tabela_multa['fim_vigencia_infracao'])

tabela_multa['hora_infracao']= pd.to_datetime(
    tabela_multa['hora_infracao'], format='mixed', errors='coerce')

**Categóricas**

In [ ]:
tabela_multa['assinatura_do_auto']= tabela_multa['assinatura_do_auto'].astype('category') #3
tabela_multa['indicador_de_abordagem']= tabela_multa['indicador_de_abordagem'].astype('category') #2
tabela_multa['sentido_trafego']= tabela_multa['sentido_trafego'].astype('category') #2
tabela_multa['uf_infracao']= tabela_multa['uf_infracao'].astype('category') #27
tabela_multa['indicador_veiculo_estrangeiro']= tabela_multa['indicador_veiculo_estrangeiro'].astype('category') #2

**Numéricos**

In [ ]:
tabela_multa['qtd_infracoes']= tabela_multa['qtd_infracoes'].astype('Int64')

In [ ]:
tabela_multa.info()

<class 'pandas.DataFrame'>
MultiIndex: 4285542 entries, (np.int64(2025), '6bf84970d11e700') to (np.int64(2018), nan)
Data columns (total 24 columns):
 #   Column                         Dtype
---  ------                         -----
 0   data_da_infracao_(dd/mm/aaaa)  datetime64[us]
 1   indicador_de_abordagem         category
 2   assinatura_do_auto             category
 3   sentido_trafego                category
 4   uf_infracao                    category
 5   br_infracao                    int64
 6   km_infracao                    int64
 7   municipio                      str
 8   indicador_veiculo_estrangeiro  category
 9   uf_placa                       str
 10  descricao_especie_veiculo      str
 11  descricao_marca_veiculo        str
 12  descricao_tipo_veiculo         str
 13  descricao_modelo_veiculo       str
 14  codigo_da_infracao             int64
 15  descricao_abreviada_infracao   str
 16  enquadramento_da_infracao      str
 17  inicio_vigencia_da_infracao    datetime64[us]
 18  fim_vigencia_infracao          datetime64[us]
 19  medicao_infracao               object
 20  hora_infracao                  datetime64[ns]
 21  medicao_considerada            object
 22  excesso_verificado             object
 23  qtd_infracoes                  Int64
dtypes: Int64(1), category(5), datetime64[ns](1), datetime64[us](3), int64(3), object(3), str(8)
memory usage: 694.3+ MB

### **Decodificação das Variáveis Categóricas**

In [ ]:
def substituicao(x):
    if x.strip()== 'C':
        return 'Houve abordagem'
    elif x.strip()=='S':
        return 'Não houve abordagem'

tabela_multa['indicador_de_abordagem']= tabela_multa['indicador_de_abordagem'].apply(substituicao)

In [ ]:
def substituicao1(x):
    if x== 'S':
        return 'Sim'
    elif x== 'N':
        return 'Não'

tabela_multa['assinatura_do_auto']= tabela_multa['assinatura_do_auto'].apply(substituicao1)

In [ ]:
def substituicao2(x):
    if x=='C':
        return 'Crescente'
    elif x== 'D':
        return 'Decrescente'

tabela_multa['sentido_trafego']= tabela_multa['sentido_trafego'].apply(substituicao2)

In [ ]:
def substituicao3(x):
    if x=='S':
        return 'Sim'
    elif x=='N':
        return 'Não'

tabela_multa['indicador_veiculo_estrangeiro']= tabela_multa['indicador_veiculo_estrangeiro'].apply(substituicao3)

## **Exportação dos arquivos para `CSV`**

In [ ]:
tabela_acidentes.to_csv('tabela_acidentes_final.csv')

In [ ]:
tabela_multa.to_csv('tabela_multa_final.csv')

## **Classificação de variáveis categóricas**

`dia_semana`

A variável `dia_semana` é **qualitativa nominal**, pois representa categorias correspondentes aos dias da semana, como segunda-feira, terça-feira e quarta-feira.

Embora os dias possam ser organizados em uma sequência cronológica, essa sequência não representa uma hierarquia ou uma ordem de grandeza entre as categorias. Não é possível afirmar que segunda-feira é maior ou menor que terça-feira.

`fase_dia`

A variável `fase_dia` é **qualitativa ordinal**, pois representa categorias relacionadas ao momento do dia, como `Pleno dia`, `Anoitecer` e `Plena noite`.

Essas categorias podem ser organizadas em uma sequência relacionada a luminosidade e a progressão do horário do dia. Entretanto, não existe uma distância numérica definida entre elas.

Essa variável pode ser armazenada como texto ou categoria, mas pode receber uma ordem específica. Por exemplo, no Pandas, seria possível definir uma ordem entre as categorias para facilitar análises e gráficos.

`idade`

A variável `idade` é **quantitativa contínua**, pois representa uma medida numérica que pode, em sua natureza, assumir qualquer valor dentro de um intervalo.

Por exemplo, uma pessoa pode ter 17 anos, 17,5 anos ou 17 anos e 3 meses. Mesmo quando a idade é registrada no dataset apenas em anos completos, a variável continua sendo naturalmente contínua.

`veiculos`

A variável `veiculos` é **quantitativa discreta**, pois representa uma contagem da quantidade de veículos envolvidos em uma ocorrência.

Ela pode assumir valores inteiros, como 1, 2, 3 ou 4 veículos, mas não valores intermediários. Por exemplo, não é possível existir 2,5 veículos envolvidos em um acidente.

## **Codificação das varáveis categóricas**

Para substituir os valores categóricos de `fase_dia`, eu optei por usar uma função e através dessa função usar a função de mapeamento `apply`. Respeitando a gradação da luz do dia.

In [ ]:
def substituicao(x):
    if x== 'Amanhecer':
        return 1
    elif x== 'Pleno dia':
        return 2
    elif x== 'Anoitecer':
        return 3
    elif x== 'Plena noite':
        return 4
    elif not x:
        return None

tabela_acidentes['fase_dia']= tabela_acidentes['fase_dia'].apply(substituicao)

In [ ]:
dicionario= {'Amanhecer': 1, 'Pleno dia': 2, 'Anoitecer': 3, 'Plena Noite': 4}
dicionario= pd.DataFrame(dicionario, index=[1])
dicionario

   Amanhecer  Pleno dia  Anoitecer  Plena Noite
1          1          2          3            4

In [ ]:
tabela_acidentes.head(5)

                 pesid data_inversa    dia_semana   horario  uf   br     km  \
ano  id
2025 652493.0  1467686   2025-01-01  quarta-feira  06:20:00  SP  116  225.0
     652519.0  1467833   2025-01-01  quarta-feira  07:50:00  CE  116  546.2
     652522.0  1468042   2025-01-01  quarta-feira  08:45:00  PR  369   88.2
     652544.0  1467849   2025-01-01  quarta-feira  11:00:00  PR  116   74.0
     652549.0  1467791   2025-01-01  quarta-feira  09:30:00  MG  251  471.0

                           municipio  \
ano  id
2025 652493.0              GUARULHOS
     652519.0              PENAFORTE
     652522.0      CORNELIO PROCOPIO
     652544.0  CAMPINA GRANDE DO SUL
     652549.0           FRANCISCO SA

                                         causa_acidente  \
ano  id
2025 652493.0  Reação tardia ou ineficiente do condutor
     652519.0                          Pista esburacada
     652522.0  Reação tardia ou ineficiente do condutor
     652544.0  Reação tardia ou ineficiente do condutor
     652549.0                   Velocidade Incompatível

                           tipo_acidente  ...           sexo ilesos  \
ano  id                                   ...
2025 652493.0                 Tombamento  ...  Não Informado      0
     652519.0            Colisão frontal  ...      Masculino      1
     652522.0           Colisão traseira  ...      Masculino      1
     652544.0  Saída de leito carroçável  ...      Masculino      1
     652549.0            Colisão frontal  ...      Masculino      1

              feridos_leves feridos_graves mortos      latitude     longitude  \
ano  id
2025 652493.0             0              0      0  -23,48586772  -46,54075317
     652519.0             0              0      0     -7,812288  -39,08333306
     652522.0             0              0      0    -23,182565    -50,637228
     652544.0             0              0      0  -25,36517687  -49,04223028
     652549.0             0              0      0  -16,46801304  -43,43121303

               regional delegacia             uop
ano  id
2025 652493.0   SPRF-SP  DEL01-SP  UOP01-DEL01-SP
     652519.0   SPRF-CE  DEL05-CE  UOP03-DEL05-CE
     652522.0   SPRF-PR  DEL07-PR  UOP05-DEL07-PR
     652544.0   SPRF-PR  DEL01-PR  UOP02-DEL01-PR
     652549.0   SPRF-MG  DEL12-MG  UOP01-DEL12-MG

[5 rows x 34 columns]

## **Categorização da coluna `idade`**

Apliquei o mesmo principio da tarefa anterior, usando funções e mapeamentos.

In [ ]:
def substituicao(x):
    if 0<=x<18:
        return 'Menores de Idade'
    elif 18<=x<30:
        return 'Jovens'
    elif 30<=x<60:
        return 'Adultos'
    elif 60<=x<120:
        return 'Idosos'

tabela_acidentes['faixa_etaria']= tabela_acidentes['idade'].apply(substituicao)

## **Frequencia das variáveis categóricas**

In [ ]:
fi= tabela_acidentes['faixa_etaria'].value_counts()
fr= (tabela_acidentes['faixa_etaria'].value_counts(normalize=True)*100)
Fi= fi.cumsum()
Fr= fr.cumsum()
total= tabela_acidentes['faixa_etaria'].value_counts().sum()

In [ ]:
tabela= pd.DataFrame(
    {'fi': fi, 'fr(%)': fr, 'Fi': Fi, 'Fr(%)': Fr},
    index=['Adultos', 'Menores de Idade', 'Jovens', 'Idosos']
)

total= pd.DataFrame({
    'fi': fi.sum(),
    'fr(%)': fr.sum(),
    'Fi': '-',
    'Fr(%)': '-' 
}, index=['Total'])

pd.concat([tabela, total])

                       fi       fr(%)       Fi      Fr(%)
Adultos            701628   49.123362   701628  49.123362
Menores de Idade   309573   21.674258  1011201  70.797621
Jovens             298631   20.908172  1309832  91.705792
Idosos             118466    8.294208  1428298      100.0
Total             1428298  100.000000        -          -

## **Resposta às perguntas:**

Os adultos de **18 a 30 anos** são os mais envolvidos em acidentes, com **701.628 registros** nessa faixa etária.

Em relação à proporção de pessoas com menos de 60 anos, considerando todas as categorias anteriores à faixa dos idosos, elas representam **91,7%** do total de pessoas envolvidas em acidentes.

A **frequência acumulada** pode ser utilizada para responder perguntas que envolvem critérios de inclusão ou exclusão de faixas etárias, como:

* Quantos acidentados tinham **até 50 anos**?
* Quantos acidentados tinham **pelo menos 50 anos**?

Essas informações podem ajudar a identificar as faixas etárias mais vulneráveis e direcionar esforços de conscientização e prevenção para os grupos com maior participação nas ocorrências.